baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Elia Ravella'
theme = "m10c"

[params]
  author = "Elia Ravella"
  description = "Generic personal blog talking about stuff I like to nerd about."
  
  [params.style]
    darkestColor = "#d35050"
    darkColor = "#212121"
    lightColor = "#f5e3e0"
    lightestColor = "#f5f5f5"
    primaryColor = "#ffffff"

  [[params.social]]
    icon = "github"
    name = "My Github"
    url = "https://github.com/rave98"
  
